# Generated by Django 4.1.2 on 2022-11-06 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_remove_song_artiste_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lyrics',
            name='song_id',
        ),
    ]
